[tool.black]
line-length = 120
target-version = ['py38']

# regex
exclude = '''/^\..+/'''

[tool.pyright]
include = ["src"]
exclude = [
  '**/__pycache__/',
  '**/node_modules/',
  '**/.git/',
  '**/.tox',
]

pythonVersion = '3.8'
reportIncompatibleMethodOverride = false

